### PR TITLE
Fix for eve v19

### PR DESCRIPTION
**Pull request by jblemee**
Fix Issue : https://github.com/Xanthos-Code/vintel/issues/183

### CODE REVIEW

**Comment by creepa7** [comment]
how can i make your fix working as non-coding noob ?

**Comment by jblemee** [comment]
You can download my unofficial release here https://github.com/jblemee/vintel/releases

**Comment by 31Intel31** [comment]
I'm using version 2.0.1. But vintel can't detect my current system. It is also impossible to specify manually - when you click on the map, it seems to be updated. What could be the problem?

**Comment by kvzylint** [comment]
Yay!!! Vintel is Back! Going to try to get it running later.

**Comment by jblemee** [comment]
cleanup

**Pull request closed without merging**
